name: Build Offline ERP App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npx electron-builder --windows nsis --publish never

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: offline-erp-installer
          path: dist/*.exe
